export const dictionary = [
    "kiasu",
    "blur",
    "atas",
    "shiok",
    "lepak",
    "sabo",
    "hawker",
    "aiyah",
    "ahbeng",
    "sotong",
    "alamak",
    "bochap",
    "bojio",
    "boliao",
    "boleh",
    "cheem",
    "chope",
    "huat",
    "jialat",
    "kaypoh",
    "lobang",
    "paiseh",
    "wayang",
    "zhng",
    "tolong",
    "dabao",
    "swee",
    "siao",
    "makan",
];

export const colourMapping: any = {
    kiasu: "bg-red-200",
    blur: "bg-yellow-200",
    atas: "bg-purple-200",
    shiok: "bg-pink-200",
    lepak: "bg-indigo-200",
    sabo: "bg-teal-200",
    hawker: "bg-orange-200",
    aiyah: "bg-lime-200",
    ahbeng: "bg-amber-200",
    sotong: "bg-cyan-200",
    alamak: "bg-blue-200",
    bochap: "bg-green-200",
    bojio: "bg-orange-100",
    boliao: "bg-fuchsia-200",
    boleh: "bg-rose-200",
    cheem: "bg-violet-200",
    chope: "bg-sky-200",
    huat: "bg-green-200",
    jialat: "bg-blue-200",
    kaypoh: "bg-pink-300",
    lobang: "bg-red-300",
    paiseh: "bg-yellow-300",
    wayang: "bg-teal-300",
    zhng: "bg-amber-300",
    tolong: "bg-indigo-300",
    dabao: "bg-purple-300",
    swee: "bg-lime-400",
    siao: "bg-orange-400",
    makan: "bg-pink-400",
};
